/*
 * This source file was generated by the Gradle 'init' task
 */
package ticket.booking;

import com.fasterxml.jackson.databind.jsonFormatVisitors.JsonFormatTypes;
import ticket.booking.Services.UserBookingService;
import ticket.booking.entities.Train;
import ticket.booking.entities.User;
import ticket.booking.util.UserServiceUtil;

import java.io.IOException;
import java.util.*;
import java.util.function.Predicate;
import java.util.stream.Collectors;

public class App {
    public static void main(String[] args){
        System.out.println("Running Train Booking System");
        Scanner sc = new Scanner(System.in);
        int option = 0 ;
        UserBookingService userBookingService = null ;
        try {
            userBookingService = new UserBookingService();
        }catch(IOException ex){
            System.out.println("there is something wrong ");
           // ex.printStackTrace();
        }
        Train trainSelectedForBooking = null;
        String source=null ;
        String dest=null ;

        while(option!=7){
            System.out.println("Choose Option");
            System.out.println("1. Sign Up");
            System.out.println("2. Login");
            System.out.println("3. Fetch Bookings");
            System.out.println("4. Search Trains ");
            System.out.println("5. Book a seat");
            System.out.println("6. Cancel my Booking");
            System.out.println("7. Exit the App");
            option = sc.nextInt();


            switch (option){
                case 1 :
                    System.out.println("Enter the username to signup ");
                    String nameToSignup = sc.next();
                    System.out.println("Enter password :");
                    String passwordToSignup = sc.next();

                    User userToSignup = new User(nameToSignup,passwordToSignup, UserServiceUtil.hashPassword(passwordToSignup),new ArrayList<>(), UUID.randomUUID().toString());

                    userBookingService.signUp(userToSignup);
                    break ;

                case 2 :
                    System.out.println("enter your username to login : ");
                    String nameToLogin = sc.next();
                    System.out.println("enter your password : ");
                    String passwordToLogin = sc.next();
                   User userToLogin = new User(nameToLogin,passwordToLogin,UserServiceUtil.hashPassword(passwordToLogin),new ArrayList<>(),UUID.randomUUID().toString());

                    try{
                        userBookingService = new UserBookingService(userToLogin);
                       Boolean isLoggedIn =  userBookingService.loginUser();

                       if(isLoggedIn){
                           System.out.println("Login Successful");
                       }
                       else{
                           System.out.println("Invalid username or password . ");
                       }
                    }
                    catch (IOException ex){
                        return;
                    }
                    break ;

                case 3 :
                    System.out.println("Fetching your bookings ");

                    userBookingService.fetchBooking();
                    break;

                case 4:
                    System.out.println("Enter your source station : ");
                     source = sc.next();
                    System.out.println("Enter your destination ");
                     dest = sc.next() ;
                    List<Train>trains = userBookingService.getTrains(source , dest);
                    if(trains.isEmpty()){
                        System.out.println("No train found");
                    }
                    else {
                        int index = 1;
                        for (Train t : trains) {
                            System.out.println(index + ". Train id : " + t.getTrainId());

                            System.out.println("Station" + " ".repeat(10) + "Time");
                            for (Map.Entry<String, String> operator : t.getStationTimes().entrySet()) {
                                System.out.println(operator.getKey() + " ".repeat(10) + operator.getValue());
                            }
                            index++;
                        }
                        System.out.println("Select a train by typing 1, 2, 3....");
                        trainSelectedForBooking = trains.get(sc.nextInt()-1);
                    }
                        break;

                case 5:
                    if(trainSelectedForBooking==null){
                        System.out.println("first select the train");
                        break;
                    }
                    else {

                        System.out.println("Select a seat out of these seats");
                        List<List<Integer>> seats = userBookingService.fetchSeats(trainSelectedForBooking);
                        for (List<Integer> row : seats) {
                            for (Integer val : row) {
                                System.out.print(val + " ");
                            }
                            System.out.println();
                        }
                        System.out.println("Tell about your desired seat through row and column : ");
                        System.out.println("Enter row : ");
                        int row = sc.nextInt() - 1;
                        System.out.println("Enter column : ");
                        int column = sc.nextInt() - 1;
                        System.out.println("Booking your seat....");
                        Boolean booked = userBookingService.bookSeat(row, column, trainSelectedForBooking);
                        if (booked.equals(Boolean.TRUE)) {
                            userBookingService.createTicket(source, dest, trainSelectedForBooking);
                            System.out.println("Booked! Enjoy your journey");
                        } else {
                            System.out.println("Can't book this seat .");
                        }
                        break;
                    }
                case 6:
                    String ticketId = sc.next();
                    Boolean cancelled =userBookingService.cancelBooking(ticketId);
                    if(cancelled){
                        System.out.println("cancellation successfull");
                        break ;
                    }
                    System.out.println("cancellation failed . ");
                    break ;

                case 7 :
                    System.out.println("Closing app . ");
                    return ;

                default:
                    break;



            }
        }



    }
}
